name: InjectionExample

settings:
  base:
    SWIFT_VERSION: '6.0'
  configs:
    Release:
      SWIFT_COMPILATION_MODE: 'wholemodule'

options:
  bundleIdPrefix: com.injection
  xcodeVersion: 16.3
  usesTabs: false
  indentWidth: 4
  deploymentTarget:
    iOS: 18.4

targets:
  InjectionExample:
    type: application
    platform: iOS
    settings:
      base:
        DISPLAY_NAME: "InjectionExample"
    info:
      path: InjectionExample/Info.plist
      properties:
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSAllowsArbitraryLoadsInWebContent: true
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: "Default Configuration"
                UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
    sources:
      - path: README.md
        buildPhase: none
      - path: InjectionExample
        buildPhase: sources
        createIntermediateGroups: true
        excludes:
          - Info.plist
    preBuildScripts:
      - name: Injection
        basedOnDependencyAnalysis: false
        script: |
                export PATH=$PATH:${SRCROOT}/../.build/release/
                swift-wiring inject `find ${SRCROOT} -name "*.wire.swift" | tr '\n' ' '` -o ${SCRIPT_OUTPUT_FILE_0}
        outputFiles:
          - $(SRCROOT)/InjectionExample/Generated/Containers.generated.swift
    buildRules:
      - name: Filtering
        filePattern: "*.wire.swift"
        script: |
                export PATH=$PATH:${SRCROOT}/../.build/release/
                swift-wiring filter -i ${INPUT_FILE_PATH} -o ${SCRIPT_OUTPUT_FILE_0}
        outputFiles:
          - $(DERIVED_FILE_DIR)/$(INPUT_FILE_BASE).filtered.swift
