import Foundation
import ArgumentParser
import SwiftSyntax
import SwiftParser

struct InjectCommand: ParsableCommand {

    static let configuration = CommandConfiguration(
        commandName: "inject",
        abstract: "Use this command to generate Swift files with Container implementations"
    )

    @Argument(help: "Input Swift files")
    var inputFiles: [String]

    @Option(name: .customShort("o"), help: "Container output file")
    var containerOutputFile: String

    func run() {
        let console = ConsoleOutput()

        do {
            let sourceFiles = try inputFiles.map { fileName in
                try SourceDefinition(fileName: fileName, tree: try SourceFileReader.parse(file: fileName))
            }

            let resolvedContainers = try DependencyResolver(sources: sourceFiles).resolvedContainers

            // FIXME: Remove potential duplicated imports
            let resultSource = resolvedContainers
                .map {
                    ContainerOutput(resolvedContainer: $0).generateSource().description
                }
                .joined(separator: "\n\n")

            let output = """
            // AUTOGENERATED FILE, DO NOT MODIFY!  
                
            \(resultSource)
            """

            try output.write(to: URL(fileURLWithPath: containerOutputFile), atomically: true, encoding: .utf8)
        } catch {
            console.fatalError(error)
        }
    }
}
